#Project Makefile
all:
	python3 main.py
	python3 profiling.py
clean:
pack:
	#TODO	
test:
	python3 test_mathlib.py
run:
	#ma to spoustet program
	python3 main.py
doc: 
	#dokumentace
profile:
	python3 profiling.py

