#Project Makefile
.PHONY all clean pack test run doc profile
	
all:
	python3 main.py
	python3 profiling.py
clean:

pack:
	#TODO	
test:
	python3 test_mathlib.py
run:
	#ma to spoustet program
	python3 main.py
doc:
	doxygen Doxyfile
	
profile:
	python3 profiling.py

