#Project Makefile
all:
	python3 main.py
	python3 profiling.py
clean:
	
test:
	test_mathlib.py
	#python3 mathlib.py
	#python3 profiling.py
run:
	#ma to spoustet program
	python3 mathlib.py
doc: 
	#dokumentace
profile:
	python3 profiling.py
UI:
	python3 UI_template.py
